### ISSUE TITLE
Error happens: invalid literal for int() with base 10: 'May19-May31'

### ISSUE THREAD

**Issue by mekhovov** [miguelpuyol/Jira-Alfred-Workflow#6]
when trying to get `List Jira Issues` error happens:

<img width="541" alt="screen shot 2015-09-30 at 01 49 17" src="https://cloud.githubusercontent.com/assets/194539/10181227/cbc4abe2-6715-11e5-963a-23a7b59bb9d8.png">

I think we are using `string` in our jira but code expects `int` here :(

can we fix this? :)

**Comment by miguelpuyol** [comment]
I would need to get more info about the error. Could you show me the workflow log?

Here is how to get it: https://www.alfredapp.com/help/workflows/advanced/debugger/

Make sure you remove private info from the log, if any

**Comment by mekhovov** [comment]
@miguelpuyol this is workflow log: https://gist.github.com/mekhovov/78aaab086b8eb395e390
thanks!

**Comment by miguelpuyol** [comment]
I cannot see it! I get a 404

On Wed, Oct 7, 2015 at 3:22 AM, Mekhovov Alexander <notifications@github.com

> wrote:
> 
> @miguelpuyol https://github.com/miguelpuyol this is workflow log:
> https://gist.github.com/mekhovov/49f774e70a9b32f93217
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/miguelpuyol/Jira-Alfred-Workflow/issues/6#issuecomment-146049791
> .

## 

Miguel García Puyol

**Comment by mekhovov** [comment]
@miguelpuyol added here:

Starting debug for 'Jira Task Manager'

``````
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 03:18:25 workflow.py:1386 DEBUG    Reading settings from `/Users/alex/Library/Application Support/Alfred 2/Workflow Data/com.miguelpuyol.jira/settings.json` ...
03:18:25 workflow.py:2323 DEBUG    Got password : jira@alfred:xxx
WARNING:root:('Connection aborted.', error(60, 'Operation timed out')) while doing GET http://xxx.yyy/rest/api/2/serverInfo [{u'headers': {'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.7.0 CPython/2.7.10 Darwin/15.0.0', 'Connection': 'keep-alive', u'X-Atlassian-Token': u'no-check', u'Cache-Control': u'no-cache', u'Content-Type': u'application/json'}, 'params': None}]
WARNING:root:Got ConnectionError [('Connection aborted.', error(60, 'Operation timed out'))] errno:None on GET http://xxx.yyy/rest/api/2/serverInfo
{'request': <PreparedRequest [GET]>, 'response': None}\{'request': <PreparedRequest [GET]>, 'response': None}
WARNING:root:Got recoverable error from GET http://xxx.yyy/rest/api/2/serverInfo, will retry [1/3] in 10s. Err: ('Connection aborted.', error(60, 'Operation timed out'))
03:19:07 workflow.py:1960 DEBUG    Workflow version : 0.4.0
DEBUG:workflow:Workflow version : 0.4.0
03:19:07 jira.py:199 INFO     []
INFO:workflow:[]
03:19:07 jira.py:51 INFO     Retrieving the sprints from JIRA
INFO:workflow:Retrieving the sprints from JIRA
03:19:08 workflow.py:1978 ERROR    invalid literal for int() with base 10: 'May19-May31'
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.13735306-6458-44A7-ABD2-0CFBE1C89553/workflow/workflow.py", line 1971, in run
    func(self)
  File "jira.py", line 240, in main
    list_incomplete_stories(args.query)
  File "jira.py", line 30, in list_incomplete_stories
    incompleted_stories = get_incompleted_stories()
  File "jira.py", line 67, in get_incompleted_stories
    current_sprint = get_current_sprint()
  File "jira.py", line 59, in get_current_sprint
    sprints = get_sprints()
  File "jira.py", line 54, in get_sprints
    key=lambda x: int(x.name.split(' ')[1]), reverse=latest_first)
  File "jira.py", line 54, in <lambda>
    key=lambda x: int(x.name.split(' ')[1]), reverse=latest_first)
ValueError: invalid literal for int() with base 10: 'May19-May31'
ERROR:workflow:invalid literal for int() with base 10: 'May19-May31'
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.13735306-6458-44A7-ABD2-0CFBE1C89553/workflow/workflow.py", line 1971, in run
    func(self)
  File "jira.py", line 240, in main
    list_incomplete_stories(args.query)
  File "jira.py", line 30, in list_incomplete_stories
    incompleted_stories = get_incompleted_stories()
  File "jira.py", line 67, in get_incompleted_stories
    current_sprint = get_current_sprint()
  File "jira.py", line 59, in get_current_sprint
    sprints = get_sprints()
  File "jira.py", line 54, in get_sprints
    key=lambda x: int(x.name.split(' ')[1]), reverse=latest_first)
  File "jira.py", line 54, in <lambda>
    key=lambda x: int(x.name.split(' ')[1]), reverse=latest_first)
ValueError: invalid literal for int() with base 10: 'May19-May31'
03:19:08 workflow.py:1996 DEBUG    Workflow finished in 0.905 seconds.
DEBUG:workflow:Workflow finished in 0.905 seconds.```
``````

**Comment by miguelpuyol** [comment]
There is an ugly error in the code.

I will try to fix it and commit a new version soon

**Comment by miguelpuyol** [comment]
Can you try with the new binary file? https://github.com/miguelpuyol/Jira-Alfred-Workflow/blob/master/Jira%20Task%20Manager.alfredworkflow

**Comment by mekhovov** [comment]
@miguelpuyol  yeah! it works! many thanks!!!!
