### ISSUE TITLE
requests module is missing

### ISSUE THREAD

**Issue by ptillemans** [miguelpuyol/Jira-Alfred-Workflow#8]
When running the script it immediately fails with:

[ERROR: alfred.workflow.input.scriptfilter] Code 1: Traceback (most recent call last):
  File "jira.py", line 7, in <module>
    from lib.jira import JIRA
  File "/Users/pti/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CD36A112-90DF-4427-8159-EBE9B7883F7E/lib/jira/**init**.py", line 5, in <module>
    from lib.jira.config import get_jira
  File "/Users/pti/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CD36A112-90DF-4427-8159-EBE9B7883F7E/lib/jira/config.py", line 17, in <module>
    from lib.jira.client import JIRA
  File "/Users/pti/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CD36A112-90DF-4427-8159-EBE9B7883F7E/lib/jira/client.py", line 43, in <module>
    import requests
ImportError: No module named requests

**Comment by miguelpuyol** [comment]
Could you try installing the request module by execuing `pip install requests` on a terminal?

**Comment by piotrkorlaga** [comment]
i got the same issue

**Comment by miguelpuyol** [comment]
Could you solve it by installing the module? Have you tried the latest version of the workflow?
