### ISSUE TITLE
feature request: support https server urls

### ISSUE THREAD

**Issue by cogell** [miguelpuyol/Jira-Alfred-Workflow#9]

**Comment by miguelpuyol** [comment]
Hi @cogell I have it working with a https server...

**Comment by cogell** [comment]
hm! perhaps my 404 error is from a different source.

I dropped into the code to see that I need to supply an `http` server url on setup: https://github.com/miguelpuyol/Jira-Alfred-Workflow/blob/54e2b08598416848c65dbc1d3e9a85919bc920f2/jira-setup.py#L53

That got my connection working. Then I choose the sprint board I wanted. Then when I tried to load up my tickets/stories I get this error (copy pasted from the alfred debug console):

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 11:17:25 workflow.py:1386 DEBUG    Reading settings from `/Users/ccogell13/Library/Application Support/Alfred 2/Workflow Data/com.miguelpuyol.jira/settings.json` ...
11:17:25 workflow.py:2323 DEBUG    Got password : jira@alfred:ccogell
/Users/ccogell13/Google Drive/appsync/alfred/Alfred.alfredpreferences/workflows/user.workflow.9C34B0AA-AF3A-40F2-8543-FA80B0EB0442/lib/jira/client.py:280: UserWarning: You are running an outdated version of JIRA Python 1.0.1. Current version is 1.0.3. Do not file any bugs against older versions.
  __version__, released_version))
11:17:27 workflow.py:1960 DEBUG    Workflow version : 0.4.0
11:17:27 jira.py:215 INFO     []
11:17:27 jira.py:50 INFO     Retrieving the sprints from JIRA
11:17:28 workflow.py:1978 ERROR    JiraError HTTP 404
    url: https://huffpost.atlassian.net/rest/greenhopper/1.0/sprintquery/None?includeHistoricSprints=true&includeFutureSprints=true
    response headers = {/** omitted less I expose some session key that doesnt expire quickly **/}
    response text = 
Traceback (most recent call last):
  File "/Users/ccogell13/Google Drive/appsync/alfred/Alfred.alfredpreferences/workflows/user.workflow.9C34B0AA-AF3A-40F2-8543-FA80B0EB0442/workflow/workflow.py", line 1971, in run
    func(self)
  File "jira.py", line 260, in main
    list_incomplete_stories(args.query)
  File "jira.py", line 30, in list_incomplete_stories
    incompleted_stories = get_incompleted_stories()
  File "jira.py", line 66, in get_incompleted_stories
    current_sprint = get_current_sprint()
  File "jira.py", line 58, in get_current_sprint
    sprints = get_sprints()
  File "jira.py", line 51, in get_sprints
    sprints = jira.sprints(board_id)
  File "/Users/ccogell13/Google Drive/appsync/alfred/Alfred.alfredpreferences/workflows/user.workflow.9C34B0AA-AF3A-40F2-8543-FA80B0EB0442/lib/jira/client.py", line 91, in wrapper
    result = func(*arg_list, **kwargs)
  File "/Users/ccogell13/Google Drive/appsync/alfred/Alfred.alfredpreferences/workflows/user.workflow.9C34B0AA-AF3A-40F2-8543-FA80B0EB0442/lib/jira/client.py", line 2507, in sprints
    base=self.AGILE_BASE_URL)
  File "/Users/ccogell13/Google Drive/appsync/alfred/Alfred.alfredpreferences/workflows/user.workflow.9C34B0AA-AF3A-40F2-8543-FA80B0EB0442/lib/jira/client.py", line 2033, in _get_json
    r = self._session.get(url, params=params)
  File "/Users/ccogell13/Google Drive/appsync/alfred/Alfred.alfredpreferences/workflows/user.workflow.9C34B0AA-AF3A-40F2-8543-FA80B0EB0442/lib/jira/resilientsession.py", line 80, in get
    return self.__verb('GET', url, **kwargs)
  File "/Users/ccogell13/Google Drive/appsync/alfred/Alfred.alfredpreferences/workflows/user.workflow.9C34B0AA-AF3A-40F2-8543-FA80B0EB0442/lib/jira/resilientsession.py", line 76, in __verb
    raise_on_error(r, verb=verb, **kwargs)
  File "/Users/ccogell13/Google Drive/appsync/alfred/Alfred.alfredpreferences/workflows/user.workflow.9C34B0AA-AF3A-40F2-8543-FA80B0EB0442/lib/jira/utils.py", line 120, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
JIRAError: JiraError HTTP 404
    url: https://huffpost.atlassian.net/rest/greenhopper/1.0/sprintquery/None?includeHistoricSprints=true&includeFutureSprints=true
    response headers = {'X-AUSERNAME': 'ccogell', 'X-AREQUESTID': '677x177886x1', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding':
```

**Comment by miguelpuyol** [comment]
The URL seems weird with /None on it... 

Do you have an active sprint?

**Comment by miguelpuyol** [comment]
Maybe the Board ID is incorrect?

**Comment by cogell** [comment]
Now I'm getting back "No sprint found" when we are definitely in an active sprint. 

I'm able to retrieve specific tickets with the current info when hitting `jira --story XYZ-123`. In the alfred debug window I get `UserWarning: You are running an outdated version of JIRA Python 1.0.1. Current version is 1.0.3. Do not file any bugs against older versions.` I forked this repo and bumped the version but dont know how to make the `.alfredworkflow` file with this new change. Thoughts?

**Comment by miguelpuyol** [comment]
I guess you you set up the right board id but could you double check it?

I have not updated the workflow in a while so that warning is "normal"

**Comment by cogell** [comment]
I double double checked the board id. It is correct. I'll have to dig more into the what is happening.

Can you tell me how to generate the `.alfredworkflow` in your repo?

**Comment by miguelpuyol** [comment]
check the part of export your workflow of this blog post:

http://computers.tutsplus.com/tutorials/alfred-workflows-for-beginners--mac-55446
